add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="yagpdb"
host="localhost"
user="yagpdb"
pass="ihateducks"
sslmode="disable"
whitelist=["commands_channels_overrides","commands_command_overrides"]